### ISSUE TITLE
Update team member profiles and projects

### ISSUE THREAD

**Issue by hongyuanjia** [ideas-lab-nus/lab-website#12]
TODOs:

### Update projects:
1. [x] Remove all current project pages @hongyuanjia 
2. [ ] Add updates for prejects including:
    1. [x] COVID-19 project  @Joycewx @LeonXU7
    2. [x] MPC related @JamesCheng21 
    3. [x] Kajima project @leiyue812 
    4. [x] Resilience project @hongyuanjia 
    5. [x] Life-cycle cost optimization @rainysunday0728 
    6. [ ] Data segment project @MahmoudAbdelRahman 
    7. [ ] Visual programming @MahmoudAbdelRahman 
    8. [x] SDE4 project @hongyuanjia @rainysunday0728 
    9. [x] eplusr, epluspar and epwshitr related @hongyuanjia 
    10. [ ] COVID-19 Dorms GANs @MahmoudAbdelRahman 

### Update lab member profiles
1. [x] Lei Xu @LeonXU7 
1. [x] Wenxin Li @Joycewx 
1. [x] Shuxu Qin @1ChristinaQin

**Comment by MahmoudAbdelRahman** [comment]
**Building lifecycle automatic data segmentation using natural language processing.** 
We use the state-of-the-art Natural Language Processing (NLP) methods to extract useful data from over 20,000 research articles. This data is then automatically clustered and segmented. This process helps identifying what data requirements for different building stakeholders during different lifecycle phases. 

**COVID-19 Dorms GANs**

**Comment by hongyuanjia** [comment]
@MahmoudAbdelRahman Are there any updates on other projects you are currently working on?
